---

- name: Install required software
  yum: name={{ item }} state=present
  become: true
  with_items:
    - httpd
    - mysql-server
    - php
    - php-mysql
    - php-devel
    - php-gd
    - php-pecl-memcache
    - php-pspell
    - php-snmp
    - php-xmlrpc
    - MySQL-python
    - python-devel
    - mysql-devel
    - gcc
    - gcc-c++
    - rpm-build
- name: pip install mysql python
  become: true
  command: pip install MySQL-python
